version: "3"
services:
  db:
    container_name: relationdb
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata12:/var/lib/postgressql/data

volumes:
  pgdata12: {} 
